// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents the access granted for a given Resource Pattern in an ACL.
public struct AclEntry: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The principal. Specified as Google Cloud account, with the Kafka
  /// StandardAuthorizer prefix "User:". For example:
  /// "User:test-kafka-client@test-project.iam.gserviceaccount.com".
  /// Can be the wildcard "User:*" to refer to all users.
  public var principal: Swift.String = Swift.String()

  /// Required. The permission type. Accepted values are (case insensitive):
  /// ALLOW, DENY.
  public var permissionType: Swift.String = Swift.String()

  /// Required. The operation type. Allowed values are (case insensitive): ALL,
  /// READ, WRITE, CREATE, DELETE, ALTER, DESCRIBE, CLUSTER_ACTION,
  /// DESCRIBE_CONFIGS, ALTER_CONFIGS, and IDEMPOTENT_WRITE. See
  /// https://kafka.apache.org/documentation/#operations_resources_and_protocols
  /// for valid combinations of resource_type and operation for different Kafka
  /// API requests.
  public var operation: Swift.String = Swift.String()

  /// Required. The host. Must be set to "*" for Managed Service for Apache
  /// Kafka.
  public var host: Swift.String = Swift.String()

  /// Initialize a new instance of `AclEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AclEntry().with { $0.principal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.AclEntry"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
