// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An Apache Kafka cluster deployed in a location.
public struct Cluster: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the cluster. Structured like:
  /// projects/{project_number}/locations/{location}/clusters/{cluster_id}
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the cluster was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the cluster was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Capacity configuration for the Kafka cluster.
  public var capacityConfig: CapacityConfig? = nil

  /// Optional. Rebalance configuration for the Kafka cluster.
  public var rebalanceConfig: RebalanceConfig? = nil

  /// Output only. The current state of the cluster.
  public var state: Cluster.State = Cluster.State()

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool? = nil

  /// Optional. TLS configuration for the Kafka cluster.
  public var tlsConfig: TlsConfig? = nil

  /// Platform specific configuration properties for a Kafka cluster.
  public var platformConfig: OneOf_PlatformConfig? = nil

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.gcpConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcpConfig = "gcpConfig"
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case capacityConfig = "capacityConfig"
    case rebalanceConfig = "rebalanceConfig"
    case state = "state"
    case satisfiesPzi = "satisfiesPzi"
    case satisfiesPzs = "satisfiesPzs"
    case tlsConfig = "tlsConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.capacityConfig = try container.decodeIfPresent(
      CapacityConfig.self, forKey: .capacityConfig)
    self.rebalanceConfig = try container.decodeIfPresent(
      RebalanceConfig.self, forKey: .rebalanceConfig)
    self.state = try container.decode(Cluster.State.self, forKey: .state)
    self.satisfiesPzi = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi)
    self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
    self.tlsConfig = try container.decodeIfPresent(TlsConfig.self, forKey: .tlsConfig)

    var platformConfig: OneOf_PlatformConfig? = nil
    let platformConfigCheckAndSet = {
      if platformConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'platformConfig'"))
      }
      platformConfig = $0
    }
    if let gcpConfig = try container.decodeIfPresent(GcpConfig?.self, forKey: .gcpConfig) {
      try platformConfigCheckAndSet(.gcpConfig(gcpConfig))
    }
    self.platformConfig = platformConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.capacityConfig, forKey: .capacityConfig)
    try container.encode(self.rebalanceConfig, forKey: .rebalanceConfig)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.tlsConfig, forKey: .tlsConfig)

    if let choice = self.platformConfig {
      switch choice {
      case .gcpConfig(let value):
        try container.encode(value, forKey: .gcpConfig)
      }
    }
  }

  /// The state of the cluster.
  public enum State: Codable, Equatable, Sendable {
    /// A state was not specified.
    case unspecified
    /// The cluster is being created.
    case creating
    /// The cluster is active.
    case active
    /// The cluster is being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .active: return 2
      case .deleting: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .active: return "ACTIVE"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "ACTIVE": self = .active
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .active
      case 3: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .active: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Platform specific configuration properties for a Kafka cluster.
  public enum OneOf_PlatformConfig: Codable, Equatable, Sendable {
    /// Required. Configuration properties for a Kafka cluster deployed to Google
    /// Cloud Platform.
    indirect case gcpConfig(GcpConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.Cluster"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
