// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Configuration properties for a Kafka Connect cluster deployed to Google Cloud
/// Platform.
public struct ConnectGcpConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Access configuration for the Kafka Connect cluster.
  public var accessConfig: ConnectAccessConfig? = nil

  /// Optional. Secrets to load into workers. Exact SecretVersions from Secret
  /// Manager must be provided -- aliases are not supported. Up to 32 secrets may
  /// be loaded into one cluster. Format:
  /// projects/<project-id>/secrets/<secret-name>/versions/<version-id>
  public var secretPaths: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConnectGcpConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectGcpConfig().with { $0.accessConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accessConfig = CodingKeys(stringValue: "accessConfig")
    static let secretPaths = CodingKeys(stringValue: "secretPaths")

    static let _knownKeys: Set<Swift.String> = [
      "accessConfig",
      "secretPaths",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.accessConfig = try container.decodeIfPresent(
      ConnectAccessConfig.self, forKey: .accessConfig)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .secretPaths) {
      self.secretPaths = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.accessConfig, forKey: .accessConfig)
    try container.encode(self.secretPaths, forKey: .secretPaths)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.ConnectGcpConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
