// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A Kafka Connect connector in a given ConnectCluster.
public struct Connector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the connector.
  /// Structured like:
  /// projects/{project}/locations/{location}/connectClusters/{connect_cluster}/connectors/{connector}
  public var name: Swift.String = Swift.String()

  /// Optional. Connector config as keys/values.
  /// The keys of the map are connector property names, for example:
  /// `connector.class`, `tasks.max`, `key.converter`.
  public var configs: [Swift.String: Swift.String] = [:]

  /// Output only. The current state of the connector.
  public var state: Connector.State = Connector.State()

  /// A policy that specifies how to restart the failed connectors/tasks in a
  /// Cluster resource. If not set, the failed connectors/tasks won't be
  /// restarted.
  public var restartPolicy: OneOf_RestartPolicy? = nil

  /// Initialize a new instance of `Connector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connector().with { $0.taskRestartPolicy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case taskRestartPolicy = "taskRestartPolicy"
    case name = "name"
    case configs = "configs"
    case state = "state"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.configs = try container.decode([Swift.String: Swift.String].self, forKey: .configs)
    self.state = try container.decode(Connector.State.self, forKey: .state)

    var restartPolicy: OneOf_RestartPolicy? = nil
    let restartPolicyCheckAndSet = {
      if restartPolicy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'restartPolicy'"))
      }
      restartPolicy = $0
    }
    if let taskRestartPolicy = try container.decodeIfPresent(
      TaskRetryPolicy?.self, forKey: .taskRestartPolicy)
    {
      try restartPolicyCheckAndSet(.taskRestartPolicy(taskRestartPolicy))
    }
    self.restartPolicy = restartPolicy
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.configs, forKey: .configs)
    try container.encode(self.state, forKey: .state)

    if let choice = self.restartPolicy {
      switch choice {
      case .taskRestartPolicy(let value):
        try container.encode(value, forKey: .taskRestartPolicy)
      }
    }
  }

  /// The state of the connector.
  public enum State: Codable, Equatable, Sendable {
    /// A state was not specified.
    case unspecified
    /// The connector is not assigned to any tasks, usually transient.
    case unassigned
    /// The connector is running.
    case running
    /// The connector has been paused.
    case paused
    /// The connector has failed. See logs for why.
    case failed
    /// The connector is restarting.
    case restarting
    /// The connector has been stopped.
    case stopped
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unassigned: return 1
      case .running: return 2
      case .paused: return 3
      case .failed: return 4
      case .restarting: return 5
      case .stopped: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .unassigned: return "UNASSIGNED"
      case .running: return "RUNNING"
      case .paused: return "PAUSED"
      case .failed: return "FAILED"
      case .restarting: return "RESTARTING"
      case .stopped: return "STOPPED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "UNASSIGNED": self = .unassigned
      case "RUNNING": self = .running
      case "PAUSED": self = .paused
      case "FAILED": self = .failed
      case "RESTARTING": self = .restarting
      case "STOPPED": self = .stopped
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unassigned
      case 2: self = .running
      case 3: self = .paused
      case 4: self = .failed
      case 5: self = .restarting
      case 6: self = .stopped
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .unassigned: return try container.encode(1)
      case .running: return try container.encode(2)
      case .paused: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .restarting: return try container.encode(5)
      case .stopped: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// A policy that specifies how to restart the failed connectors/tasks in a
  /// Cluster resource. If not set, the failed connectors/tasks won't be
  /// restarted.
  public enum OneOf_RestartPolicy: Codable, Equatable, Sendable {
    /// Optional. Restarts the individual tasks of a Connector.
    indirect case taskRestartPolicy(TaskRetryPolicy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.Connector"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
