// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The configuration of a Virtual Private Cloud (VPC) network that can access
/// the Kafka Connect cluster.
public struct ConnectNetworkConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. VPC subnet to make available to the Kafka Connect cluster.
  /// Structured like:
  /// projects/{project}/regions/{region}/subnetworks/{subnet_id}
  ///
  /// It is used to create a Private Service Connect (PSC) interface for the
  /// Kafka Connect workers. It must be located in the same region as the
  /// Kafka Connect cluster.
  ///
  /// The CIDR range of the subnet must be within the IPv4 address ranges for
  /// private networks, as specified in RFC 1918. The primary subnet CIDR range
  /// must have a minimum size of /22 (1024 addresses).
  public var primarySubnet: Swift.String = Swift.String()

  /// Optional. Additional subnets may be specified. They may be in another
  /// region, but must be in the same VPC network. The Connect workers can
  /// communicate with network endpoints in either the primary or additional
  /// subnets.
  public var additionalSubnets: [Swift.String] = []

  /// Optional. Additional DNS domain names from the subnet's network to be made
  /// visible to the Connect Cluster. When using MirrorMaker2, it's necessary to
  /// add the bootstrap address's dns domain name of the target cluster to make
  /// it visible to the connector. For example:
  /// my-kafka-cluster.us-central1.managedkafka.my-project.cloud.goog
  public var dnsDomainNames: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConnectNetworkConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectNetworkConfig().with { $0.primarySubnet = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let primarySubnet = CodingKeys(stringValue: "primarySubnet")
    static let additionalSubnets = CodingKeys(stringValue: "additionalSubnets")
    static let dnsDomainNames = CodingKeys(stringValue: "dnsDomainNames")

    static let _knownKeys: Set<Swift.String> = [
      "primarySubnet",
      "additionalSubnets",
      "dnsDomainNames",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .primarySubnet) {
      self.primarySubnet = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .additionalSubnets) {
      self.additionalSubnets = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dnsDomainNames) {
      self.dnsDomainNames = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.primarySubnet, forKey: .primarySubnet)
    try container.encode(self.additionalSubnets, forKey: .additionalSubnets)
    try container.encode(self.dnsDomainNames, forKey: .dnsDomainNames)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.ConnectNetworkConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
