// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Kafka consumer group in a given cluster.
public struct ConsumerGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the consumer group. The `consumer_group` segment is
  /// used when connecting directly to the cluster. Structured like:
  /// projects/{project}/locations/{location}/clusters/{cluster}/consumerGroups/{consumer_group}
  public var name: Swift.String = Swift.String()

  /// Optional. Metadata for this consumer group for all topics it has metadata
  /// for. The key of the map is a topic name, structured like:
  /// projects/{project}/locations/{location}/clusters/{cluster}/topics/{topic}
  public var topics: [Swift.String: ConsumerTopicMetadata] = [:]

  /// Initialize a new instance of `ConsumerGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConsumerGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.ConsumerGroup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
