// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for CreateConnectCluster.
public struct CreateConnectClusterRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent project/location in which to create the Kafka Connect
  /// cluster. Structured like
  /// `projects/{project}/locations/{location}/`.
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for the Connect cluster, which will become the
  /// final component of the cluster's name. The ID must be 1-63 characters long,
  /// and match the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` to comply
  /// with RFC 1035.
  ///
  /// This value is structured like: `my-cluster-id`.
  public var connectClusterId: Swift.String = Swift.String()

  /// Required. Configuration of the Kafka Connect cluster to create. Its `name`
  /// field is ignored.
  public var connectCluster: ConnectCluster? = nil

  /// Optional. An optional request ID to identify requests. Specify a unique
  /// request ID to avoid duplication of requests. If a request times out or
  /// fails, retrying with the same ID allows the server to recognize the
  /// previous attempt. For at least 60 minutes, the server ignores duplicate
  /// requests bearing the same ID.
  ///
  /// For example, consider a situation where you make an initial request and the
  /// request times out. If you make the request again with the same request ID
  /// within 60 minutes of the last request, the server checks if an original
  /// operation with the same request ID was received. If so, the server ignores
  /// the second request.
  ///
  /// The request ID must be a valid UUID. A zero UUID is not supported
  /// (00000000-0000-0000-0000-000000000000).
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateConnectClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateConnectClusterRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.CreateConnectClusterRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
