// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request for CreateAcl.
public struct CreateAclRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent cluster in which to create the acl.
  /// Structured like
  /// `projects/{project}/locations/{location}/clusters/{cluster}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for the acl, which will become the final component
  /// of the acl's name. The structure of `acl_id` defines the Resource Pattern
  /// (resource_type, resource_name, pattern_type) of the acl. `acl_id` is
  /// structured like one of the following:
  ///
  /// For acls on the cluster:
  ///   `cluster`
  ///
  /// For acls on a single resource within the cluster:
  ///   `topic/{resource_name}`
  ///   `consumerGroup/{resource_name}`
  ///   `transactionalId/{resource_name}`
  ///
  /// For acls on all resources that match a prefix:
  ///   `topicPrefixed/{resource_name}`
  ///   `consumerGroupPrefixed/{resource_name}`
  ///   `transactionalIdPrefixed/{resource_name}`
  ///
  /// For acls on all resources of a given type (i.e. the wildcard literal "*"):
  ///   `allTopics` (represents `topic/*`)
  ///   `allConsumerGroups` (represents `consumerGroup/*`)
  ///   `allTransactionalIds` (represents `transactionalId/*`)
  public var aclId: Swift.String = Swift.String()

  /// Required. Configuration of the acl to create. Its `name` field is ignored.
  public var acl: Acl? = nil

  /// Initialize a new instance of `CreateAclRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAclRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.CreateAclRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
