// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class ManagedKafkaConnectRetry: ManagedKafkaConnectStub {
    let inner: any ManagedKafkaConnectStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any ManagedKafkaConnectStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listConnectClusters(
      request: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConnectClustersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse
          in
          return try await self.inner.listConnectClusters(request: r, options: o)
        })
    }

    public func getConnectCluster(
      request: GetConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ConnectCluster
          in
          return try await self.inner.getConnectCluster(request: r, options: o)
        })
    }

    public func createConnectCluster(
      request: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnectCluster(request: r, options: o)
        })
    }

    public func updateConnectCluster(
      request: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnectCluster(request: r, options: o)
        })
    }

    public func deleteConnectCluster(
      request: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnectCluster(request: r, options: o)
        })
    }

    public func listConnectors(
      request: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConnectorsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListConnectorsResponse
          in
          return try await self.inner.listConnectors(request: r, options: o)
        })
    }

    public func getConnector(
      request: GetConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Connector
          in
          return try await self.inner.getConnector(request: r, options: o)
        })
    }

    public func createConnector(
      request: CreateConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Connector
          in
          return try await self.inner.createConnector(request: r, options: o)
        })
    }

    public func updateConnector(
      request: UpdateConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Connector
          in
          return try await self.inner.updateConnector(request: r, options: o)
        })
    }

    public func deleteConnector(
      request: DeleteConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteConnector(request: r, options: o)
        })
    }

    public func pauseConnector(
      request: PauseConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: PauseConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.PauseConnectorResponse
          in
          return try await self.inner.pauseConnector(request: r, options: o)
        })
    }

    public func resumeConnector(
      request: ResumeConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ResumeConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse
          in
          return try await self.inner.resumeConnector(request: r, options: o)
        })
    }

    public func restartConnector(
      request: RestartConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RestartConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.RestartConnectorResponse
          in
          return try await self.inner.restartConnector(request: r, options: o)
        })
    }

    public func stopConnector(
      request: StopConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.StopConnectorResponse
          in
          return try await self.inner.stopConnector(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
