// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The service that a client application uses to manage Apache Kafka Connect
/// clusters and connectors.
///
/// @Snippet(path: "ManagedKafkaConnectQuickstart")
public class ManagedKafkaConnectClient: Clients.ManagedKafkaConnectProtocol {
  let inner: any Clients.ManagedKafkaConnectStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ManagedKafkaConnectClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ManagedKafkaConnectStub = try Clients.ManagedKafkaConnectTransport(
      options)
    inner = Clients.ManagedKafkaConnectRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ManagedKafkaConnectLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists the Kafka Connect clusters in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListConnectClusters")
  public func listConnectClusters(
    request: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse {
    try await self.inner.listConnectClusters(request: request, options: options)
  }

  /// Lists the Kafka Connect clusters in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListConnectClusters")
  public func listConnectClusters(
    byItem: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ConnectCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listConnectClusters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the properties of a single Kafka Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_GetConnectCluster")
  public func getConnectCluster(
    request: GetConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster {
    try await self.inner.getConnectCluster(request: request, options: options)
  }

  /// Creates a new Kafka Connect cluster in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_CreateConnectCluster")
  public func createConnectCluster(
    request: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnectCluster(request: request, options: options)
  }

  /// Creates a new Kafka Connect cluster in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_CreateConnectCluster")
  public func createConnectCluster(
    withPolling: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectCluster>.State in
      return try op._extractStatus(ConnectCluster.self)
    }
    let rawOp = try await self.createConnectCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the properties of a single Kafka Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_UpdateConnectCluster")
  public func updateConnectCluster(
    request: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConnectCluster(request: request, options: options)
  }

  /// Updates the properties of a single Kafka Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_UpdateConnectCluster")
  public func updateConnectCluster(
    withPolling: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectCluster>.State in
      return try op._extractStatus(ConnectCluster.self)
    }
    let rawOp = try await self.updateConnectCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectCluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_DeleteConnectCluster")
  public func deleteConnectCluster(
    request: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnectCluster(request: request, options: options)
  }

  /// Deletes a single Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_DeleteConnectCluster")
  public func deleteConnectCluster(
    withPolling: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConnectCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the connectors in a given Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListConnectors")
  public func listConnectors(
    request: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse {
    try await self.inner.listConnectors(request: request, options: options)
  }

  /// Lists the connectors in a given Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListConnectors")
  public func listConnectors(
    byItem: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Connector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listConnectors(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the properties of a single connector.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_GetConnector")
  public func getConnector(
    request: GetConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    try await self.inner.getConnector(request: request, options: options)
  }

  /// Creates a new connector in a given Connect cluster.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_CreateConnector")
  public func createConnector(
    request: CreateConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    try await self.inner.createConnector(request: request, options: options)
  }

  /// Updates the properties of a connector.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_UpdateConnector")
  public func updateConnector(
    request: UpdateConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    try await self.inner.updateConnector(request: request, options: options)
  }

  /// Deletes a connector.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_DeleteConnector")
  public func deleteConnector(
    request: DeleteConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteConnector(request: request, options: options)
  }

  /// Pauses the connector and its tasks.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_PauseConnector")
  public func pauseConnector(
    request: PauseConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse {
    try await self.inner.pauseConnector(request: request, options: options)
  }

  /// Resumes the connector and its tasks.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ResumeConnector")
  public func resumeConnector(
    request: ResumeConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse {
    try await self.inner.resumeConnector(request: request, options: options)
  }

  /// Restarts the connector.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_RestartConnector")
  public func restartConnector(
    request: RestartConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse {
    try await self.inner.restartConnector(request: request, options: options)
  }

  /// Stops the connector.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_StopConnector")
  public func stopConnector(
    request: StopConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse {
    try await self.inner.stopConnector(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ManagedKafkaConnect_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafkaConnect_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafkaConnect_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafkaConnect_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafkaConnect_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ManagedKafkaConnectClient`.
  ///
  /// To mock `ManagedKafkaConnectClient` change your functions to receive
  /// `some ManagedKafkaConnectProtocol` or `any ManagedKafkaConnectProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ManagedKafkaConnectProtocol {
    /// See `ManagedKafkaConnectClient.listConnectClusters`.
    func listConnectClusters(request: ListConnectClustersRequest) async throws
      -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse

    /// See `ManagedKafkaConnectClient.listConnectClusters`.
    func listConnectClusters(
      byItem: ListConnectClustersRequest
    ) throws -> any AsyncSequence<ConnectCluster, Swift.Error>

    /// See `ManagedKafkaConnectClient.listConnectClusters`.
    func listConnectClusters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ConnectCluster, Swift.Error>

    /// See `ManagedKafkaConnectClient.getConnectCluster`.
    func getConnectCluster(request: GetConnectClusterRequest) async throws
      -> GoogleCloudManagedKafkaV1.ConnectCluster

    /// See `ManagedKafkaConnectClient.getConnectCluster`.
    func getConnectCluster(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster

    /// See `ManagedKafkaConnectClient.createConnectCluster`.
    func createConnectCluster(request: CreateConnectClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ManagedKafkaConnectClient.createConnectCluster`.
    func createConnectCluster(withPolling: CreateConnectClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectCluster>

    /// See `ManagedKafkaConnectClient.createConnectCluster`.
    func createConnectCluster(
      parent: Swift.String,
      connectCluster: ConnectCluster?,
      connectClusterId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster>

    /// See `ManagedKafkaConnectClient.updateConnectCluster`.
    func updateConnectCluster(request: UpdateConnectClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ManagedKafkaConnectClient.updateConnectCluster`.
    func updateConnectCluster(withPolling: UpdateConnectClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectCluster>

    /// See `ManagedKafkaConnectClient.updateConnectCluster`.
    func updateConnectCluster(
      connectCluster: ConnectCluster?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster>

    /// See `ManagedKafkaConnectClient.deleteConnectCluster`.
    func deleteConnectCluster(request: DeleteConnectClusterRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ManagedKafkaConnectClient.deleteConnectCluster`.
    func deleteConnectCluster(withPolling: DeleteConnectClusterRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `ManagedKafkaConnectClient.deleteConnectCluster`.
    func deleteConnectCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `ManagedKafkaConnectClient.listConnectors`.
    func listConnectors(request: ListConnectorsRequest) async throws
      -> GoogleCloudManagedKafkaV1.ListConnectorsResponse

    /// See `ManagedKafkaConnectClient.listConnectors`.
    func listConnectors(
      byItem: ListConnectorsRequest
    ) throws -> any AsyncSequence<Connector, Swift.Error>

    /// See `ManagedKafkaConnectClient.listConnectors`.
    func listConnectors(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Connector, Swift.Error>

    /// See `ManagedKafkaConnectClient.getConnector`.
    func getConnector(request: GetConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.getConnector`.
    func getConnector(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.createConnector`.
    func createConnector(request: CreateConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.createConnector`.
    func createConnector(
      parent: Swift.String,
      connector: Connector?,
      connectorId: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.updateConnector`.
    func updateConnector(request: UpdateConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.updateConnector`.
    func updateConnector(
      connector: Connector?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.deleteConnector`.
    func deleteConnector(request: DeleteConnectorRequest) async throws

    /// See `ManagedKafkaConnectClient.deleteConnector`.
    func deleteConnector(
      name: Swift.String,
    ) async throws

    /// See `ManagedKafkaConnectClient.pauseConnector`.
    func pauseConnector(request: PauseConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.PauseConnectorResponse

    /// See `ManagedKafkaConnectClient.pauseConnector`.
    func pauseConnector(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse

    /// See `ManagedKafkaConnectClient.resumeConnector`.
    func resumeConnector(request: ResumeConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse

    /// See `ManagedKafkaConnectClient.resumeConnector`.
    func resumeConnector(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse

    /// See `ManagedKafkaConnectClient.restartConnector`.
    func restartConnector(request: RestartConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.RestartConnectorResponse

    /// See `ManagedKafkaConnectClient.restartConnector`.
    func restartConnector(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse

    /// See `ManagedKafkaConnectClient.stopConnector`.
    func stopConnector(request: StopConnectorRequest) async throws
      -> GoogleCloudManagedKafkaV1.StopConnectorResponse

    /// See `ManagedKafkaConnectClient.stopConnector`.
    func stopConnector(
      name: Swift.String,
    ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse

    /// See `ManagedKafkaConnectClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ManagedKafkaConnectClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ManagedKafkaConnectClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ManagedKafkaConnectClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedKafkaConnectClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedKafkaConnectClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedKafkaConnectClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `ManagedKafkaConnectClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ManagedKafkaConnectClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `ManagedKafkaConnectClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ManagedKafkaConnectClient.listConnectClusters`.
    func listConnectClusters(
      request: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse

    /// See `ManagedKafkaConnectClient.listConnectClusters`.
    func listConnectClusters(
      byItem: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ConnectCluster, Swift.Error>

    /// See `ManagedKafkaConnectClient.getConnectCluster`.
    func getConnectCluster(
      request: GetConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster

    /// See `ManagedKafkaConnectClient.createConnectCluster`.
    func createConnectCluster(
      request: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedKafkaConnectClient.createConnectCluster`.
    func createConnectCluster(
      withPolling: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster>

    /// See `ManagedKafkaConnectClient.updateConnectCluster`.
    func updateConnectCluster(
      request: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedKafkaConnectClient.updateConnectCluster`.
    func updateConnectCluster(
      withPolling: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster>

    /// See `ManagedKafkaConnectClient.deleteConnectCluster`.
    func deleteConnectCluster(
      request: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedKafkaConnectClient.deleteConnectCluster`.
    func deleteConnectCluster(
      withPolling: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `ManagedKafkaConnectClient.listConnectors`.
    func listConnectors(
      request: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse

    /// See `ManagedKafkaConnectClient.listConnectors`.
    func listConnectors(
      byItem: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Connector, Swift.Error>

    /// See `ManagedKafkaConnectClient.getConnector`.
    func getConnector(
      request: GetConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.createConnector`.
    func createConnector(
      request: CreateConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.updateConnector`.
    func updateConnector(
      request: UpdateConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector

    /// See `ManagedKafkaConnectClient.deleteConnector`.
    func deleteConnector(
      request: DeleteConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ManagedKafkaConnectClient.pauseConnector`.
    func pauseConnector(
      request: PauseConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse

    /// See `ManagedKafkaConnectClient.resumeConnector`.
    func resumeConnector(
      request: ResumeConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse

    /// See `ManagedKafkaConnectClient.restartConnector`.
    func restartConnector(
      request: RestartConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse

    /// See `ManagedKafkaConnectClient.stopConnector`.
    func stopConnector(
      request: StopConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse

    /// See `ManagedKafkaConnectClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ManagedKafkaConnectClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ManagedKafkaConnectClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ManagedKafkaConnectClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedKafkaConnectClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ManagedKafkaConnectClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ManagedKafkaConnectClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ManagedKafkaConnectProtocol {
  public func listConnectClusters(request: ListConnectClustersRequest) async throws
    -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse
  {
    try await self.listConnectClusters(request: request, options: .init())
  }

  public func listConnectClusters(
    request: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listConnectClusters(
    byItem: ListConnectClustersRequest
  ) throws -> any AsyncSequence<ConnectCluster, Swift.Error> {
    try self.listConnectClusters(byItem: byItem, options: .init())
  }

  public func listConnectClusters(
    byItem: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ConnectCluster, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnectClusters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ConnectCluster, Swift.Error> {
    let request = ListConnectClustersRequest().with {
      $0.parent = parent
    }
    return try self.listConnectClusters(byItem: request)
  }

  public func getConnectCluster(request: GetConnectClusterRequest) async throws
    -> GoogleCloudManagedKafkaV1.ConnectCluster
  {
    try await self.getConnectCluster(request: request, options: .init())
  }

  public func getConnectCluster(
    request: GetConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getConnectCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster {
    let request = GetConnectClusterRequest().with {
      $0.name = name
    }
    return try await self.getConnectCluster(request: request)
  }

  public func createConnectCluster(request: CreateConnectClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnectCluster(request: request, options: .init())
  }

  public func createConnectCluster(
    request: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createConnectCluster(withPolling: CreateConnectClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectCluster>
  {
    try await self.createConnectCluster(withPolling: withPolling, options: .init())
  }

  public func createConnectCluster(
    withPolling: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConnectCluster(
    parent: Swift.String,
    connectCluster: ConnectCluster?,
    connectClusterId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster> {
    let request = CreateConnectClusterRequest().with {
      $0.parent = parent
      $0.connectCluster = connectCluster
      $0.connectClusterId = connectClusterId
    }
    return try await self.createConnectCluster(withPolling: request)
  }

  public func updateConnectCluster(request: UpdateConnectClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConnectCluster(request: request, options: .init())
  }

  public func updateConnectCluster(
    request: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateConnectCluster(withPolling: UpdateConnectClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectCluster>
  {
    try await self.updateConnectCluster(withPolling: withPolling, options: .init())
  }

  public func updateConnectCluster(
    withPolling: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectCluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConnectCluster(
    connectCluster: ConnectCluster?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectCluster> {
    let request = UpdateConnectClusterRequest().with {
      $0.connectCluster = connectCluster
      $0.updateMask = updateMask
    }
    return try await self.updateConnectCluster(withPolling: request)
  }

  public func deleteConnectCluster(request: DeleteConnectClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnectCluster(request: request, options: .init())
  }

  public func deleteConnectCluster(
    request: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteConnectCluster(withPolling: DeleteConnectClusterRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteConnectCluster(withPolling: withPolling, options: .init())
  }

  public func deleteConnectCluster(
    withPolling: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnectCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteConnectClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteConnectCluster(withPolling: request)
  }

  public func listConnectors(request: ListConnectorsRequest) async throws
    -> GoogleCloudManagedKafkaV1.ListConnectorsResponse
  {
    try await self.listConnectors(request: request, options: .init())
  }

  public func listConnectors(
    request: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listConnectors(
    byItem: ListConnectorsRequest
  ) throws -> any AsyncSequence<Connector, Swift.Error> {
    try self.listConnectors(byItem: byItem, options: .init())
  }

  public func listConnectors(
    byItem: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Connector, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnectors(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Connector, Swift.Error> {
    let request = ListConnectorsRequest().with {
      $0.parent = parent
    }
    return try self.listConnectors(byItem: request)
  }

  public func getConnector(request: GetConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.Connector
  {
    try await self.getConnector(request: request, options: .init())
  }

  public func getConnector(
    request: GetConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    let request = GetConnectorRequest().with {
      $0.name = name
    }
    return try await self.getConnector(request: request)
  }

  public func createConnector(request: CreateConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.Connector
  {
    try await self.createConnector(request: request, options: .init())
  }

  public func createConnector(
    request: CreateConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createConnector(
    parent: Swift.String,
    connector: Connector?,
    connectorId: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    let request = CreateConnectorRequest().with {
      $0.parent = parent
      $0.connector = connector
      $0.connectorId = connectorId
    }
    return try await self.createConnector(request: request)
  }

  public func updateConnector(request: UpdateConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.Connector
  {
    try await self.updateConnector(request: request, options: .init())
  }

  public func updateConnector(
    request: UpdateConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateConnector(
    connector: Connector?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudManagedKafkaV1.Connector {
    let request = UpdateConnectorRequest().with {
      $0.connector = connector
      $0.updateMask = updateMask
    }
    return try await self.updateConnector(request: request)
  }

  public func deleteConnector(request: DeleteConnectorRequest) async throws {
    try await self.deleteConnector(request: request, options: .init())
  }

  public func deleteConnector(
    request: DeleteConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteConnector(
    name: Swift.String,
  ) async throws {
    let request = DeleteConnectorRequest().with {
      $0.name = name
    }
    try await self.deleteConnector(request: request)
  }

  public func pauseConnector(request: PauseConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.PauseConnectorResponse
  {
    try await self.pauseConnector(request: request, options: .init())
  }

  public func pauseConnector(
    request: PauseConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func pauseConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse {
    let request = PauseConnectorRequest().with {
      $0.name = name
    }
    return try await self.pauseConnector(request: request)
  }

  public func resumeConnector(request: ResumeConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse
  {
    try await self.resumeConnector(request: request, options: .init())
  }

  public func resumeConnector(
    request: ResumeConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func resumeConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse {
    let request = ResumeConnectorRequest().with {
      $0.name = name
    }
    return try await self.resumeConnector(request: request)
  }

  public func restartConnector(request: RestartConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.RestartConnectorResponse
  {
    try await self.restartConnector(request: request, options: .init())
  }

  public func restartConnector(
    request: RestartConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func restartConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse {
    let request = RestartConnectorRequest().with {
      $0.name = name
    }
    return try await self.restartConnector(request: request)
  }

  public func stopConnector(request: StopConnectorRequest) async throws
    -> GoogleCloudManagedKafkaV1.StopConnectorResponse
  {
    try await self.stopConnector(request: request, options: .init())
  }

  public func stopConnector(
    request: StopConnectorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func stopConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse {
    let request = StopConnectorRequest().with {
      $0.name = name
    }
    return try await self.stopConnector(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
