// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ManagedKafkaConnectLogging: ManagedKafkaConnectStub {
    let inner: any ManagedKafkaConnectStub
    let logger: Logger

    public init(_ inner: any ManagedKafkaConnectStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-managedkafka-v1"
      logger[metadataKey: "gcp.client.service"] = "managedkafka"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ManagedKafkaConnect"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listConnectClusters(
      request: ListConnectClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnectClusters",
        action: {
          (r: ListConnectClustersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListConnectClustersResponse
          in
          return try await self.inner.listConnectClusters(request: r, options: o)
        })
    }

    public func getConnectCluster(
      request: GetConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConnectCluster {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnectCluster",
        action: {
          (r: GetConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ConnectCluster
          in
          return try await self.inner.getConnectCluster(request: r, options: o)
        })
    }

    public func createConnectCluster(
      request: CreateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConnectCluster",
        action: {
          (r: CreateConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createConnectCluster(request: r, options: o)
        })
    }

    public func updateConnectCluster(
      request: UpdateConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConnectCluster",
        action: {
          (r: UpdateConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateConnectCluster(request: r, options: o)
        })
    }

    public func deleteConnectCluster(
      request: DeleteConnectClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConnectCluster",
        action: {
          (r: DeleteConnectClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteConnectCluster(request: r, options: o)
        })
    }

    public func listConnectors(
      request: ListConnectorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConnectorsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnectors",
        action: {
          (r: ListConnectorsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListConnectorsResponse
          in
          return try await self.inner.listConnectors(request: r, options: o)
        })
    }

    public func getConnector(
      request: GetConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnector",
        action: {
          (r: GetConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Connector
          in
          return try await self.inner.getConnector(request: r, options: o)
        })
    }

    public func createConnector(
      request: CreateConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConnector",
        action: {
          (r: CreateConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Connector
          in
          return try await self.inner.createConnector(request: r, options: o)
        })
    }

    public func updateConnector(
      request: UpdateConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Connector {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConnector",
        action: {
          (r: UpdateConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Connector
          in
          return try await self.inner.updateConnector(request: r, options: o)
        })
    }

    public func deleteConnector(
      request: DeleteConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConnector",
        action: {
          (r: DeleteConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteConnector(request: r, options: o)
        })
    }

    public func pauseConnector(
      request: PauseConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.PauseConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "pauseConnector",
        action: {
          (r: PauseConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.PauseConnectorResponse
          in
          return try await self.inner.pauseConnector(request: r, options: o)
        })
    }

    public func resumeConnector(
      request: ResumeConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "resumeConnector",
        action: {
          (r: ResumeConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ResumeConnectorResponse
          in
          return try await self.inner.resumeConnector(request: r, options: o)
        })
    }

    public func restartConnector(
      request: RestartConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.RestartConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "restartConnector",
        action: {
          (r: RestartConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.RestartConnectorResponse
          in
          return try await self.inner.restartConnector(request: r, options: o)
        })
    }

    public func stopConnector(
      request: StopConnectorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.StopConnectorResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "stopConnector",
        action: {
          (r: StopConnectorRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.StopConnectorResponse
          in
          return try await self.inner.stopConnector(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
