// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ManagedKafkaStub: Sendable {
    func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListClustersResponse

    func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Cluster

    func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listTopics(
      request: ListTopicsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListTopicsResponse

    func getTopic(
      request: GetTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic

    func createTopic(
      request: CreateTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic

    func updateTopic(
      request: UpdateTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic

    func deleteTopic(
      request: DeleteTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listConsumerGroups(
      request: ListConsumerGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse

    func getConsumerGroup(
      request: GetConsumerGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup

    func updateConsumerGroup(
      request: UpdateConsumerGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup

    func deleteConsumerGroup(
      request: DeleteConsumerGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listAcls(
      request: ListAclsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListAclsResponse

    func getAcl(
      request: GetAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl

    func createAcl(
      request: CreateAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl

    func updateAcl(
      request: UpdateAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl

    func deleteAcl(
      request: DeleteAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func addAclEntry(
      request: AddAclEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.AddAclEntryResponse

    func removeAclEntry(
      request: RemoveAclEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
