// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ManagedKafkaLogging: ManagedKafkaStub {
    let inner: any ManagedKafkaStub
    let logger: Logger

    public init(_ inner: any ManagedKafkaStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-managedkafka-v1"
      logger[metadataKey: "gcp.client.service"] = "managedkafka"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ManagedKafka"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listClusters",
        action: {
          (r: ListClustersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListClustersResponse
          in
          return try await self.inner.listClusters(request: r, options: o)
        })
    }

    public func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Cluster {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCluster",
        action: {
          (r: GetClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Cluster
          in
          return try await self.inner.getCluster(request: r, options: o)
        })
    }

    public func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCluster",
        action: {
          (r: CreateClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCluster(request: r, options: o)
        })
    }

    public func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCluster",
        action: {
          (r: UpdateClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCluster(request: r, options: o)
        })
    }

    public func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCluster",
        action: {
          (r: DeleteClusterRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCluster(request: r, options: o)
        })
    }

    public func listTopics(
      request: ListTopicsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListTopicsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTopics",
        action: {
          (r: ListTopicsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListTopicsResponse
          in
          return try await self.inner.listTopics(request: r, options: o)
        })
    }

    public func getTopic(
      request: GetTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTopic",
        action: {
          (r: GetTopicRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Topic
          in
          return try await self.inner.getTopic(request: r, options: o)
        })
    }

    public func createTopic(
      request: CreateTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTopic",
        action: {
          (r: CreateTopicRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Topic
          in
          return try await self.inner.createTopic(request: r, options: o)
        })
    }

    public func updateTopic(
      request: UpdateTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTopic",
        action: {
          (r: UpdateTopicRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Topic
          in
          return try await self.inner.updateTopic(request: r, options: o)
        })
    }

    public func deleteTopic(
      request: DeleteTopicRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTopic",
        action: { (r: DeleteTopicRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTopic(request: r, options: o)
        })
    }

    public func listConsumerGroups(
      request: ListConsumerGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConsumerGroups",
        action: {
          (r: ListConsumerGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse
          in
          return try await self.inner.listConsumerGroups(request: r, options: o)
        })
    }

    public func getConsumerGroup(
      request: GetConsumerGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConsumerGroup",
        action: {
          (r: GetConsumerGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ConsumerGroup
          in
          return try await self.inner.getConsumerGroup(request: r, options: o)
        })
    }

    public func updateConsumerGroup(
      request: UpdateConsumerGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConsumerGroup",
        action: {
          (r: UpdateConsumerGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ConsumerGroup
          in
          return try await self.inner.updateConsumerGroup(request: r, options: o)
        })
    }

    public func deleteConsumerGroup(
      request: DeleteConsumerGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConsumerGroup",
        action: {
          (r: DeleteConsumerGroupRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteConsumerGroup(request: r, options: o)
        })
    }

    public func listAcls(
      request: ListAclsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListAclsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAcls",
        action: {
          (r: ListAclsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.ListAclsResponse
          in
          return try await self.inner.listAcls(request: r, options: o)
        })
    }

    public func getAcl(
      request: GetAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAcl",
        action: {
          (r: GetAclRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Acl
          in
          return try await self.inner.getAcl(request: r, options: o)
        })
    }

    public func createAcl(
      request: CreateAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAcl",
        action: {
          (r: CreateAclRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Acl
          in
          return try await self.inner.createAcl(request: r, options: o)
        })
    }

    public func updateAcl(
      request: UpdateAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAcl",
        action: {
          (r: UpdateAclRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.Acl
          in
          return try await self.inner.updateAcl(request: r, options: o)
        })
    }

    public func deleteAcl(
      request: DeleteAclRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAcl",
        action: { (r: DeleteAclRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAcl(request: r, options: o)
        })
    }

    public func addAclEntry(
      request: AddAclEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.AddAclEntryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "addAclEntry",
        action: {
          (r: AddAclEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.AddAclEntryResponse
          in
          return try await self.inner.addAclEntry(request: r, options: o)
        })
    }

    public func removeAclEntry(
      request: RemoveAclEntryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "removeAclEntry",
        action: {
          (r: RemoveAclEntryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse
          in
          return try await self.inner.removeAclEntry(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
