// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The service that a client application uses to manage Apache Kafka clusters,
/// topics and consumer groups.
///
/// @Snippet(path: "ManagedKafkaQuickstart")
public final class ManagedKafkaClient: Clients.ManagedKafkaProtocol, Sendable {
  let inner: any Clients.ManagedKafkaStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `ManagedKafkaClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ManagedKafkaStub = try Clients.ManagedKafkaTransport(options)
    inner = Clients.ManagedKafkaRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ManagedKafkaLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists the clusters in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafka_ListClusters")
  public func listClusters(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListClustersResponse {
    try await self.inner.listClusters(request: request, options: options)
  }

  /// Returns the properties of a single cluster.
  ///
  /// @Snippet(path: "ManagedKafka_GetCluster")
  public func getCluster(
    request: GetClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Cluster {
    try await self.inner.getCluster(request: request, options: options)
  }

  /// Creates a new cluster in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafka_CreateCluster")
  public func createCluster(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCluster(request: request, options: options)
  }

  /// Creates a new cluster in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafka_CreateCluster")
  public func createClusterPollingUntilDone(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.createCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the properties of a single cluster.
  ///
  /// @Snippet(path: "ManagedKafka_UpdateCluster")
  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCluster(request: request, options: options)
  }

  /// Updates the properties of a single cluster.
  ///
  /// @Snippet(path: "ManagedKafka_UpdateCluster")
  public func updateClusterPollingUntilDone(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      return try op._extractStatus(Cluster.self)
    }
    let rawOp = try await self.updateCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single cluster.
  ///
  /// @Snippet(path: "ManagedKafka_DeleteCluster")
  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCluster(request: request, options: options)
  }

  /// Deletes a single cluster.
  ///
  /// @Snippet(path: "ManagedKafka_DeleteCluster")
  public func deleteClusterPollingUntilDone(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteCluster(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the topics in a given cluster.
  ///
  /// @Snippet(path: "ManagedKafka_ListTopics")
  public func listTopics(
    request: ListTopicsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListTopicsResponse {
    try await self.inner.listTopics(request: request, options: options)
  }

  /// Returns the properties of a single topic.
  ///
  /// @Snippet(path: "ManagedKafka_GetTopic")
  public func getTopic(
    request: GetTopicRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    try await self.inner.getTopic(request: request, options: options)
  }

  /// Creates a new topic in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafka_CreateTopic")
  public func createTopic(
    request: CreateTopicRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    try await self.inner.createTopic(request: request, options: options)
  }

  /// Updates the properties of a single topic.
  ///
  /// @Snippet(path: "ManagedKafka_UpdateTopic")
  public func updateTopic(
    request: UpdateTopicRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    try await self.inner.updateTopic(request: request, options: options)
  }

  /// Deletes a single topic.
  ///
  /// @Snippet(path: "ManagedKafka_DeleteTopic")
  public func deleteTopic(
    request: DeleteTopicRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTopic(request: request, options: options)
  }

  /// Lists the consumer groups in a given cluster.
  ///
  /// @Snippet(path: "ManagedKafka_ListConsumerGroups")
  public func listConsumerGroups(
    request: ListConsumerGroupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse {
    try await self.inner.listConsumerGroups(request: request, options: options)
  }

  /// Returns the properties of a single consumer group.
  ///
  /// @Snippet(path: "ManagedKafka_GetConsumerGroup")
  public func getConsumerGroup(
    request: GetConsumerGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
    try await self.inner.getConsumerGroup(request: request, options: options)
  }

  /// Updates the properties of a single consumer group.
  ///
  /// @Snippet(path: "ManagedKafka_UpdateConsumerGroup")
  public func updateConsumerGroup(
    request: UpdateConsumerGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
    try await self.inner.updateConsumerGroup(request: request, options: options)
  }

  /// Deletes a single consumer group.
  ///
  /// @Snippet(path: "ManagedKafka_DeleteConsumerGroup")
  public func deleteConsumerGroup(
    request: DeleteConsumerGroupRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteConsumerGroup(request: request, options: options)
  }

  /// Lists the acls in a given cluster.
  ///
  /// @Snippet(path: "ManagedKafka_ListAcls")
  public func listAcls(
    request: ListAclsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListAclsResponse {
    try await self.inner.listAcls(request: request, options: options)
  }

  /// Returns the properties of a single acl.
  ///
  /// @Snippet(path: "ManagedKafka_GetAcl")
  public func getAcl(
    request: GetAclRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    try await self.inner.getAcl(request: request, options: options)
  }

  /// Creates a new acl in the given project, location, and cluster.
  ///
  /// @Snippet(path: "ManagedKafka_CreateAcl")
  public func createAcl(
    request: CreateAclRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    try await self.inner.createAcl(request: request, options: options)
  }

  /// Updates the properties of a single acl.
  ///
  /// @Snippet(path: "ManagedKafka_UpdateAcl")
  public func updateAcl(
    request: UpdateAclRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    try await self.inner.updateAcl(request: request, options: options)
  }

  /// Deletes an acl.
  ///
  /// @Snippet(path: "ManagedKafka_DeleteAcl")
  public func deleteAcl(
    request: DeleteAclRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAcl(request: request, options: options)
  }

  /// Incremental update: Adds an acl entry to an acl. Creates the acl if it does
  /// not exist yet.
  ///
  /// @Snippet(path: "ManagedKafka_AddAclEntry")
  public func addAclEntry(
    request: AddAclEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.AddAclEntryResponse {
    try await self.inner.addAclEntry(request: request, options: options)
  }

  /// Incremental update: Removes an acl entry from an acl. Deletes the acl if
  /// its acl entries become empty (i.e. if the removed entry was the last one in
  /// the acl).
  ///
  /// @Snippet(path: "ManagedKafka_RemoveAclEntry")
  public func removeAclEntry(
    request: RemoveAclEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse {
    try await self.inner.removeAclEntry(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ManagedKafka_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ManagedKafka_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafka_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafka_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafka_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafka_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ManagedKafkaClient`.
  ///
  /// To mock `ManagedKafkaClient` change your functions to receive
  /// `some ManagedKafkaProtocol` or `any ManagedKafkaProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ManagedKafkaProtocol: Sendable {
    /// See `ManagedKafkaClient.listClusters`.
    func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListClustersResponse

    /// See `ManagedKafkaClient.getCluster`.
    func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Cluster

    /// See `ManagedKafkaClient.createCluster`.
    func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedKafkaClient.createCluster`.
    func createClusterPollingUntilDone(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `ManagedKafkaClient.updateCluster`.
    func updateCluster(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedKafkaClient.updateCluster`.
    func updateClusterPollingUntilDone(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Cluster>

    /// See `ManagedKafkaClient.deleteCluster`.
    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ManagedKafkaClient.deleteCluster`.
    func deleteClusterPollingUntilDone(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `ManagedKafkaClient.listTopics`.
    func listTopics(
      request: ListTopicsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListTopicsResponse

    /// See `ManagedKafkaClient.getTopic`.
    func getTopic(
      request: GetTopicRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic

    /// See `ManagedKafkaClient.createTopic`.
    func createTopic(
      request: CreateTopicRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic

    /// See `ManagedKafkaClient.updateTopic`.
    func updateTopic(
      request: UpdateTopicRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Topic

    /// See `ManagedKafkaClient.deleteTopic`.
    func deleteTopic(
      request: DeleteTopicRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ManagedKafkaClient.listConsumerGroups`.
    func listConsumerGroups(
      request: ListConsumerGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse

    /// See `ManagedKafkaClient.getConsumerGroup`.
    func getConsumerGroup(
      request: GetConsumerGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup

    /// See `ManagedKafkaClient.updateConsumerGroup`.
    func updateConsumerGroup(
      request: UpdateConsumerGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup

    /// See `ManagedKafkaClient.deleteConsumerGroup`.
    func deleteConsumerGroup(
      request: DeleteConsumerGroupRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ManagedKafkaClient.listAcls`.
    func listAcls(
      request: ListAclsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.ListAclsResponse

    /// See `ManagedKafkaClient.getAcl`.
    func getAcl(
      request: GetAclRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl

    /// See `ManagedKafkaClient.createAcl`.
    func createAcl(
      request: CreateAclRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl

    /// See `ManagedKafkaClient.updateAcl`.
    func updateAcl(
      request: UpdateAclRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.Acl

    /// See `ManagedKafkaClient.deleteAcl`.
    func deleteAcl(
      request: DeleteAclRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ManagedKafkaClient.addAclEntry`.
    func addAclEntry(
      request: AddAclEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.AddAclEntryResponse

    /// See `ManagedKafkaClient.removeAclEntry`.
    func removeAclEntry(
      request: RemoveAclEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse

    /// See `ManagedKafkaClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ManagedKafkaClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ManagedKafkaClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ManagedKafkaClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ManagedKafkaClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ManagedKafkaProtocol {
  public func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudManagedKafkaV1.ListClustersResponse
  {
    try await self.listClusters(request: request, options: .init())
  }

  public func listClusters(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListClustersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listClustersByItems(
    request: ListClustersRequest
  ) -> any AsyncSequence<Cluster, Swift.Error> & Sendable {
    self.listClustersByItems(request: request, options: .init())
  }

  /// Lists the clusters in a given project and location.
  ///
  /// @Snippet(path: "ManagedKafka_ListClusters")
  public func listClustersByItems(
    request: ListClustersRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Cluster, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListClustersResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listClusters(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listClustersByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Cluster, Swift.Error> & Sendable {
    let request = ListClustersRequest().with {
      $0.parent = parent
    }
    return self.listClustersByItems(request: request)
  }

  public func getCluster(request: GetClusterRequest) async throws
    -> GoogleCloudManagedKafkaV1.Cluster
  {
    try await self.getCluster(request: request, options: .init())
  }

  public func getCluster(
    request: GetClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Cluster {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Cluster {
    let request = GetClusterRequest().with {
      $0.name = name
    }
    return try await self.getCluster(request: request)
  }

  public func createCluster(request: CreateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createCluster(request: request, options: .init())
  }

  public func createCluster(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createClusterPollingUntilDone(request: CreateClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.createClusterPollingUntilDone(request: request, options: .init())
  }

  public func createClusterPollingUntilDone(
    request: CreateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createClusterPollingUntilDone(
    parent: Swift.String,
    cluster: Cluster?,
    clusterId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = CreateClusterRequest().with {
      $0.parent = parent
      $0.cluster = cluster
      $0.clusterId = clusterId
    }
    return try await self.createClusterPollingUntilDone(request: request)
  }

  public func updateCluster(request: UpdateClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateCluster(request: request, options: .init())
  }

  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateClusterPollingUntilDone(request: UpdateClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Cluster>
  {
    try await self.updateClusterPollingUntilDone(request: request, options: .init())
  }

  public func updateClusterPollingUntilDone(
    request: UpdateClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Cluster>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateClusterPollingUntilDone(
    cluster: Cluster?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Cluster> {
    let request = UpdateClusterRequest().with {
      $0.cluster = cluster
      $0.updateMask = updateMask
    }
    return try await self.updateClusterPollingUntilDone(request: request)
  }

  public func deleteCluster(request: DeleteClusterRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteCluster(request: request, options: .init())
  }

  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteClusterPollingUntilDone(request: DeleteClusterRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteClusterPollingUntilDone(request: request, options: .init())
  }

  public func deleteClusterPollingUntilDone(
    request: DeleteClusterRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteClusterPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteClusterPollingUntilDone(request: request)
  }

  public func listTopics(request: ListTopicsRequest) async throws
    -> GoogleCloudManagedKafkaV1.ListTopicsResponse
  {
    try await self.listTopics(request: request, options: .init())
  }

  public func listTopics(
    request: ListTopicsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListTopicsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listTopicsByItems(
    request: ListTopicsRequest
  ) -> any AsyncSequence<Topic, Swift.Error> & Sendable {
    self.listTopicsByItems(request: request, options: .init())
  }

  /// Lists the topics in a given cluster.
  ///
  /// @Snippet(path: "ManagedKafka_ListTopics")
  public func listTopicsByItems(
    request: ListTopicsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Topic, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListTopicsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listTopics(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTopicsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Topic, Swift.Error> & Sendable {
    let request = ListTopicsRequest().with {
      $0.parent = parent
    }
    return self.listTopicsByItems(request: request)
  }

  public func getTopic(request: GetTopicRequest) async throws -> GoogleCloudManagedKafkaV1.Topic {
    try await self.getTopic(request: request, options: .init())
  }

  public func getTopic(
    request: GetTopicRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getTopic(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    let request = GetTopicRequest().with {
      $0.name = name
    }
    return try await self.getTopic(request: request)
  }

  public func createTopic(request: CreateTopicRequest) async throws
    -> GoogleCloudManagedKafkaV1.Topic
  {
    try await self.createTopic(request: request, options: .init())
  }

  public func createTopic(
    request: CreateTopicRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createTopic(
    parent: Swift.String,
    topic: Topic?,
    topicId: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    let request = CreateTopicRequest().with {
      $0.parent = parent
      $0.topic = topic
      $0.topicId = topicId
    }
    return try await self.createTopic(request: request)
  }

  public func updateTopic(request: UpdateTopicRequest) async throws
    -> GoogleCloudManagedKafkaV1.Topic
  {
    try await self.updateTopic(request: request, options: .init())
  }

  public func updateTopic(
    request: UpdateTopicRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateTopic(
    topic: Topic?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudManagedKafkaV1.Topic {
    let request = UpdateTopicRequest().with {
      $0.topic = topic
      $0.updateMask = updateMask
    }
    return try await self.updateTopic(request: request)
  }

  public func deleteTopic(request: DeleteTopicRequest) async throws {
    try await self.deleteTopic(request: request, options: .init())
  }

  public func deleteTopic(
    request: DeleteTopicRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteTopic(
    name: Swift.String,
  ) async throws {
    let request = DeleteTopicRequest().with {
      $0.name = name
    }
    try await self.deleteTopic(request: request)
  }

  public func listConsumerGroups(request: ListConsumerGroupsRequest) async throws
    -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse
  {
    try await self.listConsumerGroups(request: request, options: .init())
  }

  public func listConsumerGroups(
    request: ListConsumerGroupsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConsumerGroupsByItems(
    request: ListConsumerGroupsRequest
  ) -> any AsyncSequence<ConsumerGroup, Swift.Error> & Sendable {
    self.listConsumerGroupsByItems(request: request, options: .init())
  }

  /// Lists the consumer groups in a given cluster.
  ///
  /// @Snippet(path: "ManagedKafka_ListConsumerGroups")
  public func listConsumerGroupsByItems(
    request: ListConsumerGroupsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<ConsumerGroup, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudManagedKafkaV1.ListConsumerGroupsResponse in
      var request = request
      request.pageToken = token
      return try await self.listConsumerGroups(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConsumerGroupsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<ConsumerGroup, Swift.Error> & Sendable {
    let request = ListConsumerGroupsRequest().with {
      $0.parent = parent
    }
    return self.listConsumerGroupsByItems(request: request)
  }

  public func getConsumerGroup(request: GetConsumerGroupRequest) async throws
    -> GoogleCloudManagedKafkaV1.ConsumerGroup
  {
    try await self.getConsumerGroup(request: request, options: .init())
  }

  public func getConsumerGroup(
    request: GetConsumerGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConsumerGroup(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
    let request = GetConsumerGroupRequest().with {
      $0.name = name
    }
    return try await self.getConsumerGroup(request: request)
  }

  public func updateConsumerGroup(request: UpdateConsumerGroupRequest) async throws
    -> GoogleCloudManagedKafkaV1.ConsumerGroup
  {
    try await self.updateConsumerGroup(request: request, options: .init())
  }

  public func updateConsumerGroup(
    request: UpdateConsumerGroupRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConsumerGroup(
    consumerGroup: ConsumerGroup?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudManagedKafkaV1.ConsumerGroup {
    let request = UpdateConsumerGroupRequest().with {
      $0.consumerGroup = consumerGroup
      $0.updateMask = updateMask
    }
    return try await self.updateConsumerGroup(request: request)
  }

  public func deleteConsumerGroup(request: DeleteConsumerGroupRequest) async throws {
    try await self.deleteConsumerGroup(request: request, options: .init())
  }

  public func deleteConsumerGroup(
    request: DeleteConsumerGroupRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConsumerGroup(
    name: Swift.String,
  ) async throws {
    let request = DeleteConsumerGroupRequest().with {
      $0.name = name
    }
    try await self.deleteConsumerGroup(request: request)
  }

  public func listAcls(request: ListAclsRequest) async throws
    -> GoogleCloudManagedKafkaV1.ListAclsResponse
  {
    try await self.listAcls(request: request, options: .init())
  }

  public func listAcls(
    request: ListAclsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.ListAclsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAclsByItems(
    request: ListAclsRequest
  ) -> any AsyncSequence<Acl, Swift.Error> & Sendable {
    self.listAclsByItems(request: request, options: .init())
  }

  /// Lists the acls in a given cluster.
  ///
  /// @Snippet(path: "ManagedKafka_ListAcls")
  public func listAclsByItems(
    request: ListAclsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Acl, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudManagedKafkaV1.ListAclsResponse in
      var request = request
      request.pageToken = token
      return try await self.listAcls(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAclsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Acl, Swift.Error> & Sendable {
    let request = ListAclsRequest().with {
      $0.parent = parent
    }
    return self.listAclsByItems(request: request)
  }

  public func getAcl(request: GetAclRequest) async throws -> GoogleCloudManagedKafkaV1.Acl {
    try await self.getAcl(request: request, options: .init())
  }

  public func getAcl(
    request: GetAclRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAcl(
    name: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    let request = GetAclRequest().with {
      $0.name = name
    }
    return try await self.getAcl(request: request)
  }

  public func createAcl(request: CreateAclRequest) async throws -> GoogleCloudManagedKafkaV1.Acl {
    try await self.createAcl(request: request, options: .init())
  }

  public func createAcl(
    request: CreateAclRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAcl(
    parent: Swift.String,
    acl: Acl?,
    aclId: Swift.String,
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    let request = CreateAclRequest().with {
      $0.parent = parent
      $0.acl = acl
      $0.aclId = aclId
    }
    return try await self.createAcl(request: request)
  }

  public func updateAcl(request: UpdateAclRequest) async throws -> GoogleCloudManagedKafkaV1.Acl {
    try await self.updateAcl(request: request, options: .init())
  }

  public func updateAcl(
    request: UpdateAclRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAcl(
    acl: Acl?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudManagedKafkaV1.Acl {
    let request = UpdateAclRequest().with {
      $0.acl = acl
      $0.updateMask = updateMask
    }
    return try await self.updateAcl(request: request)
  }

  public func deleteAcl(request: DeleteAclRequest) async throws {
    try await self.deleteAcl(request: request, options: .init())
  }

  public func deleteAcl(
    request: DeleteAclRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAcl(
    name: Swift.String,
  ) async throws {
    let request = DeleteAclRequest().with {
      $0.name = name
    }
    try await self.deleteAcl(request: request)
  }

  public func addAclEntry(request: AddAclEntryRequest) async throws
    -> GoogleCloudManagedKafkaV1.AddAclEntryResponse
  {
    try await self.addAclEntry(request: request, options: .init())
  }

  public func addAclEntry(
    request: AddAclEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.AddAclEntryResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func addAclEntry(
    acl: Swift.String,
    aclEntry: AclEntry?,
  ) async throws -> GoogleCloudManagedKafkaV1.AddAclEntryResponse {
    let request = AddAclEntryRequest().with {
      $0.acl = acl
      $0.aclEntry = aclEntry
    }
    return try await self.addAclEntry(request: request)
  }

  public func removeAclEntry(request: RemoveAclEntryRequest) async throws
    -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse
  {
    try await self.removeAclEntry(request: request, options: .init())
  }

  public func removeAclEntry(
    request: RemoveAclEntryRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func removeAclEntry(
    acl: Swift.String,
    aclEntry: AclEntry?,
  ) async throws -> GoogleCloudManagedKafkaV1.RemoveAclEntryResponse {
    let request = RemoveAclEntryRequest().with {
      $0.acl = acl
      $0.aclEntry = aclEntry
    }
    return try await self.removeAclEntry(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "ManagedKafka_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ManagedKafka_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
