// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response for RemoveAclEntry.
public struct RemoveAclEntryResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The result of removing the acl entry, depending on whether the acl was
  /// deleted as a result of removing the acl entry.
  public var result: OneOf_Result? = nil

  /// Initialize a new instance of `RemoveAclEntryResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RemoveAclEntryResponse().with { $0.acl = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case acl = "acl"
    case aclDeleted = "aclDeleted"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let acl = try container.decodeIfPresent(Acl?.self, forKey: .acl) {
      try resultCheckAndSet(.acl(acl))
    }
    if let aclDeleted = try container.decodeIfPresent(Swift.Bool.self, forKey: .aclDeleted) {
      try resultCheckAndSet(.aclDeleted(aclDeleted))
    }
    self.result = result
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.result {
      switch choice {
      case .acl(let value):
        try container.encode(value, forKey: .acl)
      case .aclDeleted(let value):
        try container.encode(value, forKey: .aclDeleted)
      }
    }
  }

  /// The result of removing the acl entry, depending on whether the acl was
  /// deleted as a result of removing the acl entry.
  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// The updated acl. Returned if the removed acl entry was not the last entry
    /// in the acl.
    indirect case acl(Acl?)
    /// Returned with value true if the removed acl entry was the last entry in
    /// the acl, resulting in acl deletion.
    case aclDeleted(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.RemoveAclEntryResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
