// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The TLS configuration for the Kafka cluster.
public struct TlsConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The configuration of the broker truststore. If specified, clients
  /// can use mTLS for authentication.
  public var trustConfig: TrustConfig? = nil

  /// Optional. A list of rules for mapping from SSL principal names to
  /// short names. These are applied in order by Kafka.
  /// Refer to the Apache Kafka documentation for `ssl.principal.mapping.rules`
  /// for the precise formatting details and syntax.
  /// Example: "RULE:^CN=(.*?),OU=ServiceUsers.*$/$1@example.com/,DEFAULT"
  ///
  /// This is a static Kafka broker configuration. Setting or modifying this
  /// field will trigger a rolling restart of the Kafka brokers to apply
  /// the change. An empty string means no rules are applied (Kafka default).
  public var sslPrincipalMappingRules: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TlsConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TlsConfig().with { $0.trustConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let trustConfig = CodingKeys(stringValue: "trustConfig")
    static let sslPrincipalMappingRules = CodingKeys(stringValue: "sslPrincipalMappingRules")

    static let _knownKeys: Set<Swift.String> = [
      "trustConfig",
      "sslPrincipalMappingRules",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.trustConfig = try container.decodeIfPresent(TrustConfig.self, forKey: .trustConfig)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .sslPrincipalMappingRules)
    {
      self.sslPrincipalMappingRules = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.trustConfig, forKey: .trustConfig)
    try container.encode(self.sslPrincipalMappingRules, forKey: .sslPrincipalMappingRules)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.TlsConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
