// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Kafka topic in a given cluster.
public struct Topic: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the topic. The `topic` segment is used when
  /// connecting directly to the cluster. Structured like:
  /// projects/{project}/locations/{location}/clusters/{cluster}/topics/{topic}
  public var name: Swift.String = Swift.String()

  /// Required. The number of partitions this topic has. The partition count can
  /// only be increased, not decreased. Please note that if partitions are
  /// increased for a topic that has a key, the partitioning logic or the
  /// ordering of the messages will be affected.
  public var partitionCount: Swift.Int32 = Swift.Int32()

  /// Required. Immutable. The number of replicas of each partition. A
  /// replication factor of 3 is recommended for high availability.
  public var replicationFactor: Swift.Int32 = Swift.Int32()

  /// Optional. Configurations for the topic that are overridden from the cluster
  /// defaults. The key of the map is a Kafka topic property name, for example:
  /// `cleanup.policy`, `compression.type`.
  public var configs: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `Topic`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Topic().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.Topic"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
