// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Kafka topic in a given cluster.
public struct Topic: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the topic. The `topic` segment is used when
  /// connecting directly to the cluster. Structured like:
  /// projects/{project}/locations/{location}/clusters/{cluster}/topics/{topic}
  public var name: Swift.String = Swift.String()

  /// Required. The number of partitions this topic has. The partition count can
  /// only be increased, not decreased. Please note that if partitions are
  /// increased for a topic that has a key, the partitioning logic or the
  /// ordering of the messages will be affected.
  public var partitionCount: Swift.Int32 = Swift.Int32()

  /// Required. Immutable. The number of replicas of each partition. A
  /// replication factor of 3 is recommended for high availability.
  public var replicationFactor: Swift.Int32 = Swift.Int32()

  /// Optional. Configurations for the topic that are overridden from the cluster
  /// defaults. The key of the map is a Kafka topic property name, for example:
  /// `cleanup.policy`, `compression.type`.
  public var configs: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Topic`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Topic().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let partitionCount = CodingKeys(stringValue: "partitionCount")
    static let replicationFactor = CodingKeys(stringValue: "replicationFactor")
    static let configs = CodingKeys(stringValue: "configs")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "partitionCount",
      "replicationFactor",
      "configs",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .partitionCount) {
      self.partitionCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .replicationFactor) {
      self.replicationFactor = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .configs)
    {
      self.configs = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.partitionCount, forKey: .partitionCount)
    try container.encode(self.replicationFactor, forKey: .replicationFactor)
    try container.encode(self.configs, forKey: .configs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.managedkafka.v1.Topic"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
